const VEHICLE_DATA =[
  {
    "vehicleId":1,
    "personFirstName":"Juan",
    "personFirstSurname":"Perez",
    "vehicleLicensePlate":"DHL333",
    "vehicleCapacity":35.50,
    "vehicleType":"Minibus",
    "vehiclePrice":100.25,
    "vehicleStatus":"Disponible",
    "vehicleBrand":"Mercedes Benz",
    "vehicleModel":"A",
    "driverCompany":null,
    "images":"4cf0d408681a5b28ddbb099e9bcfb8a5.jpg"
  },

  {
    "vehicleId":2,
    "personFirstName":"Adrian",
    "personFirstSurname":"Ramirez",
    "vehicleLicensePlate":"WRA231",
    "vehicleCapacity":35.50,
    "vehicleType":"Minibus",
    "vehiclePrice":100.25,
    "vehicleStatus":"Disponible",
    "vehicleBrand":"Toyota",
    "vehicleModel":"Corolla",
    "driverCompany":"LA NUEVA SEGUROS",
    "images":"4cf0d408681a5b28ddbb099e9bcfb8a5.jpg"
  },
  {
    "vehicleId":3,
    "personFirstName":"Pedro",
    "personFirstSurname":"Canaviri",
    "vehicleLicensePlate":"ASQ789",
    "vehicleCapacity": 35.844590,
    "vehicleType": "Camioneta",
    "vehiclePrice": 100.25,
    "vehicleStatus": "Disponible",
    "vehicleBrand": "Nissan",
    "vehicleModel": "NT 400",
    "driverCompany":"LA NUEVA SEGUROS",
    "images":"3cf0d408681a5b28ddbb099e9bcfb8a5.jpg",
  },
  {
    "vehicleId":1,
    "personFirstName":"Juan",
    "personFirstSurname":"Perez",
    "vehicleLicensePlate":"DHL333",
    "vehicleCapacity":35.50,
    "vehicleType":"Minibus",
    "vehiclePrice":100.25,
    "vehicleStatus":"Disponible",
    "vehicleBrand":"Mercedes Benz",
    "vehicleModel":"A",
    "driverCompany":null,
    "images":"4cf0d408681a5b28ddbb099e9bcfb8a5.jpg"
  },

  {
    "vehicleId":2,
    "personFirstName":"Adrian",
    "personFirstSurname":"Ramirez",
    "vehicleLicensePlate":"WRA231",
    "vehicleCapacity":35.50,
    "vehicleType":"Minibus",
    "vehiclePrice":100.25,
    "vehicleStatus":"Disponible",
    "vehicleBrand":"Toyota",
    "vehicleModel":"Corolla",
    "driverCompany":"LA NUEVA SEGUROS",
    "images":"4cf0d408681a5b28ddbb099e9bcfb8a5.jpg"
  },
  {
    "vehicleId":3,
    "personFirstName":"Pedro",
    "personFirstSurname":"Canaviri",
    "vehicleLicensePlate":"ASQ789",
    "vehicleCapacity": 35.844590,
    "vehicleType": "Camioneta",
    "vehiclePrice": 100.25,
    "vehicleStatus": "Disponible",
    "vehicleBrand": "Nissan",
    "vehicleModel": "NT 400",
    "driverCompany":"LA NUEVA SEGUROS",
    "images":"3cf0d408681a5b28ddbb099e9bcfb8a5.jpg",
  },
];